apiVersion: v1
kind: service
metadata:
  name: shipping
  namespace: roboshop
spec: 
  selector:
    app: shipping
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetport: 8080  #container-port