apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    project: roboshop
    tier: db
spec:
  ports:
  - portocol: TCP
    port: 27017
    targetport: 27017
  clusterIP: None
  selector:
    app: mongodb
    project: roboshop
    tier: db