apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    app: mysql
    project: roboshop
    tier: db
spec:
  ports:
  - portocol: TCP
    port: 3306
    targetport: 3306
  clusterIP: None
  selector:
    app: mysql
    project: roboshop
    tier: db