apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    app: redis
    project: roboshop
    tier: db
spec:
  ports:
  - portocol: TCP
    port: 6379
    targetport: 6379
  clusterIP: None
  selector:
    app: redis
    project: roboshop
    tier: db