apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namemspace: roboshop
  labels: # these labels are deployment lables
    app: payment
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels: # these labels are used to find the pods
      app: payment
      project: roboshop
      tier: app
  template:
    metadata:
      labels: # these labels are pod labels
        app: payment
        project: roboshop
        tier: app
    spec:
      containers:
      - name: payment
        image: "gurava1234/payment:{{ .values.deployment.imageversion }}"
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"
            memory: "128Mi"
          limits:
            cpu: "100m"
            memory: "256Mi"
         envFrom:
         - secretRef:
           name: payment