apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    app: rabbitmq
    project: roboshop
    tier: db
spec:
  ports:
  - portocol: TCP
    port: 5672
    targetport: 5672
  clusterIP: None
  selector:
    app: rabbitmq
    project: roboshop
    tier: db